version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    working_dir: /app
    depends_on:
      - app
    volumes:
      - ./:/app
      - ./logs/nginx-logs:/var/log/nginx
      - ./docker/nginx/vhost/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    extra_hosts:
      - "pandich.loc:127.0.0.1"
    networks:
      - app-network
  app:
    container_name: server
    image: webfoza/node-part-1:latest
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge